services:
  mysql_db_data:
    image: mysql:5.7
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ezougla
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - backend_network

  back-end:
    build: ./ezougla-back
    container_name: ezougla_backend
    volumes:
      - backend:/app/ezougla-back
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "mysql://root:root@mysql_db_data:3306/ezougla"
    command: >
      sh -c 'until nc -z -v -w30 mysql_db_data 3306; do echo "En attente de MySQL..."; sleep 1; done && npx prisma migrate reset --force && npx prisma db push && npm run build && npm run start:dev'
    depends_on:
      - mysql_db_data
    networks:
      - backend_network

  front-end:
    build: ./ezougla-front
    container_name: ezougla_frontend
    depends_on:
      - back-end
    volumes:
      - frontend:/app/ezougla-front
    ports:
      - 4200:4200
    command: "ng serve --host 0.0.0.0 --port 4200"
    networks:
      - backend_network

  test:
    build: ./ezougla-back
    container_name: ezougla_test
    volumes:
      - test:/app
    depends_on:
      - back-end
    networks:
      - backend_network
    command: "echo 'Running tests...'"

volumes:
  db_data:
  backend:
  frontend:
  sonarqube:
  test:


networks:
  backend_network:
    driver: bridge
